package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/ioutil"
	"log"
	"os"
	"strings"
)

var (
	flagSource = flag.String("source", "", "go source file")
	fset       *token.FileSet
)

// Usage is a replacement usage function for the flags package.
func Usage() {
	fmt.Fprintf(os.Stderr, "Usage of struct2oas:\n")
	fmt.Fprintf(os.Stderr, "Flags:\n")
	flag.PrintDefaults()
}

func main() {
	log.SetFlags(0)
	log.SetPrefix("struct2oas: ")
	flag.Usage = Usage
	flag.Parse()

	log.Printf("Read source %q\n", *flagSource)
	fset = token.NewFileSet()
	node, err := parser.ParseFile(fset, *flagSource, nil, parser.ParseComments)
	if err != nil {
		log.Println("Error parsing source: " + *flagSource)
		os.Exit(255)
	}

	ast.Inspect(node, func(n ast.Node) bool {
		switch t := n.(type) {
		case *ast.TypeSpec:
			if t.Name.IsExported() {
				g := Generator{}
				g.Generate(t)
				g.WriteFile()
			}
		}
		return true
	})
}

type Generator struct {
	buf  bytes.Buffer // Accumulated output.
	Name string
}

func (g *Generator) Printf(format string, args ...interface{}) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *Generator) Generate(t *ast.TypeSpec) {
	g.Name = t.Name.String()
	log.Println("Generate", t.Name)

	g.Printf("#\n# Code generated by \"struct2oas -source %s\"; DO NOT EDIT.\n#\n\n", *flagSource)
	g.Printf("%s:\n", t.Name.Name)
	g.Printf("  type: \"object\"\n")
	g.Printf("  properties:\n")

	switch s := t.Type.(type) {
	case *ast.StructType:
		for i := 0; i < len(s.Fields.List); i++ {
			log.Printf("  Prop Name: %s\tType: %s\tTag: %s\n", s.Fields.List[i].Names[0], s.Fields.List[i].Type, s.Fields.List[i].Tag.Value)
			g.Printf("    %s:\n", s.Fields.List[i].Names[0])
			g.Printf("      type: %q\n", s.Fields.List[i].Type)
			g.Printf("      description: %q\n", strings.Replace(s.Fields.List[i].Doc.Text(), "\n", "", -1))
			// ast.Print(fset, s.Fields.List[i])
		}
	}
}

func (g *Generator) WriteFile() {
	err := ioutil.WriteFile(g.Name+".yml", g.buf.Bytes(), 0644)
	if err != nil {
		log.Fatalf("writing output: %s", err)
	}
}
